### ISSUE TITLE
Add a way to run only one test file 

### ISSUE THREAD

**Issue by lyrixx** [jolicode/asynit#13]
Right now:

```
php bin/asynit src/OrganizationRoleAdminTest.php 

                                                                     
  [InvalidArgumentException]                                         
  The "src/OrganizationRoleAdminTest.php" directory does not exist.  
                                                                     

```

**Comment by kelunik** [comment]
Should probably accept multiple files as well, so `*Test.php` works automatically with bash expansion.

**Comment by Korbeil** [comment]
Quite old issue, asked @lyrixx if it was still a problem on its side, and it looks ok now.
I'm also using single file test run on some project so I think we can close the issue :wink:
